export CC=gcc

export SRC_DIR=src

export DIR=$(shell pwd)

export OUT=output

export INC=inc

export C_OBJ
export O_OBJ
all:
	cd $(SRC_DIR) && $(MAKE)
	#$(CC) -o $(OUT)/out.bin $(O_OBJ)
clean:
	cd $(SRC_DIR) && $(MAKE) clean
