#!/bin/bash
#kernel文件夹位置
kernel="/mnt/hgfs/1linux/linux/kernel"
#git仓库连接
cmd=1
while [ $cmd != "EOF" ]
do
echo -n "Please input command: "
read cmd
#//查找clk文件
if [ $cmd = "cmd1" ]
then
	for filename in $kernel/*
	do
	if [ -f "$filename" ]
	then
		name=$(basename "$filename")
		if [[ "$name" == "cpu"* ]]
		then
		echo "cpu开头的文件: $name"
	fi
	fi
	done

elif [ $cmd = "cmd2" ] #查找含clk
then
	for cfile in $kernel/*
	do
	if [ -f "$cfile" ]
	then
		filename=$(basename "$cfile")
		ext="${filename##*.}"
		if [ "$ext" =  "c" ]
		then
		grep -q "cook" "$cfile"
			if [ $? -eq 0 ]
			then 
			echo "含有cook字符的c文件：$cfile"
			continue
			fi
		fi
	fi
	done
fi
done
