#!/bin/bash
#kernel文件夹位置
echo -n "Please input kernel dir:"
read linux
kernel="$linux"
cmd=1
read_dir(){
	for file in  `ls $1`
	do
		filename=$1"/"$file
		if [ -d "$filename" ]
		then
		read_dir $filename
		elif [ -f "$filename" ]
		then
		#name=$(basename "$filename")
                ext="${file##*.}"
                	if [ "$ext" =  "c" ]
                	then
                	grep -q "clk" "$filename"
                        	if [ $? -eq 0 ]
                        	then
                        	echo "含有clk字符的c文件：$filename"
                       	 	continue
                        	fi
			fi
		fi
	done
}
while [ $cmd != "EOF" ]
do
echo -n "Please input command: "
read cmd
#//查找clk文件
if [ $cmd = "cmd1" ]
then
	find "$kernel" -iname clk*
elif [ $cmd = "cmd2" ]
then 
read_dir $kernel
elif [ $cmd = "cmd3" ]
then
tmp1=1
tem2=1
tmp3=1
	echo  "#####指定分支####"
        read tmp1
        echo "####指定文件####"
	read tmp2
	git add "$tmp2"
	echo -n "git commit -m "
	read temp3
	git commit -m "$tmp3"
        echo "push master "
        git push origin $tmp1
fi
done
