#!/bin/bash
func1(){
echo "##################################"
echo "# -a find clk* file command      #"
echo "# -b find clk string .cfile      #"
echo "# -c   set git command           #"
echo "#   exit shell is Ctrl + d       #"
echo "##################################"
}
func2(){
case $1 in
-a)
echo;echo;
echo "####output clk* file#####"
find "$kernel" -iname clk*
echo "######output finish######";;
-b)
echo;echo;
echo "###output clk string .c file####"
grep "clk" -l -r "$kernel" -nR --include=*.c
echo "#########output finish##########";;
-c)
branch=1
filename=1
commit=1
echo -n "input git branch、filename、commit:"
read branch filename commit
git checkout "$branch"
git add "$filename"
git commit -m "$commit"
git status
esac
}
kernel="/mnt/hgfs/1linux/linux"
if [ -z "$1" ]
then
func1
elif [ -n "$1" ]
then
func2 $1
fi
if [ -n "$2" ] && [ "$2" != "$1" ]
then
func2 $2
fi
if [ -n "$3" ] && [ "$3" != "$2" ] && [ "$3" != "$2" ]
then
func2 $3
fi
:<<!
#//查找clk文件
if [ $cmd = "cmd1" ]
then
	find "$kernel" -iname clk*
elif [ $cmd = "cmd2" ]
then 
	grep "clk" -l -r "$kernel" -nR --include=*.c
elif [ $cmd = "cmd3" ]
then
tmp1=1
tmp2=1
tmp3=1
	echo  "#####指定分支####"
        read tmp1
        echo "####指定文件####"
	read tmp2
	git add "$tmp2"
	echo -n "git commit -m "
	read tmp3
	git commit -m $tmp3
        echo "####push master#### "
        git push origin $tmp1
fi
done
!
