#!/bin/bash
DIR=$(pwd)
CURL_DIR=$DIR/curl-7.76.1
CURL_INS=$CURL_DIR/output
SSL_DIR=$DIR/openssl-1.1.1c
SSL_INS=$SSL_DIR/output
SSL_INC=$SSL_INS/include
SSL_LIB=$SSL_INS/lib
cd $SSL_DIR
if [ -d output ]
then
	rm -rf "$SSL_INS/*"
else
	mkdir output
fi
export PATH=$PATH:/home/chenyujie/learngit/sim_crosscompile/sysroots/x86_64-linux/usr/bin/arm-oe-linux-gnueabi

./Configure linux-armv4 --prefix=$SSL_INS --cross-compile-prefix=arm-oe-linux-gnueabi- --sysroot=/home/chenyujie/learngit/sim_crosscompile/sysroots/mdm9607-perf

make clean
make 
make install

cd $CURL_DIR
if [ -d output ]
then
	rm -rf "$CURL_INS/*"
else
	mkdir output
fi
CPPFLAGS="-I$SSL_INC" LDFLAGS="-L$SSL_LIB" LIBS="-ldl" ./configure --prefix=$CURL_INS --host=arm-linux CC="arm-oe-linux-gnueabi-gcc --sysroot=/home/chenyujie/learngit/sim_crosscompile/sysroots/mdm9607-perf" CXX=arm-oe-linux-gnueabi-g++ --with-ssl --enable-shared --enable-static --disable-dict --enable-ftp --disable-imap --disable-ldap --disable-ldaps --disable-pop3 --disable-proxy --disable-rtsp --disable-smtp --disable-telnet --disable-tftp --disable-zlib --without-ca-bundle --without-gnutls --without-libidn --without-librtmp --without-libssh2 --without-nss --without-zlib

make clean
make 
make install
cd $DIR

